from typing import Protocol


class RepoStorage(Protocol):
    """What the service needs from a storage backend.

    Objects are immutable and content-addressed; refs are the only mutable state.
    """

    def create_repo(self, repo: str, metadata: dict) -> None: ...

    def repo_exists(self, repo: str) -> bool: ...

    def get_metadata(self, repo: str) -> dict: ...

    def put_object(self, repo: str, data: bytes) -> str: ...

    def get_object(self, repo: str, object_id: str) -> bytes: ...

    def get_ref(self, repo: str, ref: str) -> str | None: ...

    def set_ref(self, repo: str, ref: str, object_id: str, expected: str | None) -> None: ...
